#!/bin/bash
set -e

# ═══════════════════════════════════════════════════════════════
# ZeroTrace Agent — One-Line Installer (Datadog-style)
#
# Usage:
#   ZT_API_KEY="zt_xxx" curl -fsSL http://<host>:5173/agent/install.sh | bash
#
# Or with tags:
#   ZT_TAGS="env:prod team:backend" ZT_API_KEY="zt_xxx" curl ... | bash
# ═══════════════════════════════════════════════════════════════

# ── Settings ──────────────────────────────────────────────────
CONTROLLER_IP=${ZEROTRACE_CONTROLLER_IP:-"202.112.237.37"}
CONTROLLER_PORT=${ZEROTRACE_CONTROLLER_PORT:-"30035"}
INGESTER_PORT=${ZEROTRACE_INGESTER_PORT:-"30033"}
SERVER_URL=${SERVER_URL:-"http://${CONTROLLER_IP}:3001"}
API_KEY=${ZT_API_KEY:-${ZEROTRACE_API_KEY:-""}}
INSTALL_SYSTEMD=${ZEROTRACE_INSTALL_SYSTEMD:-"true"}

INSTALL_DIR="/opt/zerotrace-agent"
BIN_DIR="${INSTALL_DIR}/bin"
CONFIG_DIR="${INSTALL_DIR}/etc"
LOG_DIR="${INSTALL_DIR}/var/log"
ENV_FILE="${CONFIG_DIR}/environment"
BINARY_PATH="${BIN_DIR}/zerotrace-agent"
CONFIG_PATH="${CONFIG_DIR}/zerotrace-agent.yaml"

echo "========================================"
echo " ZeroTrace Agent Installation"
echo "========================================"
echo " Controller:  ${CONTROLLER_IP}:${CONTROLLER_PORT}"
echo " Org ID:      ${ORG_ID}"
if [ -n "${API_KEY}" ]; then
    echo " API Key:     ${API_KEY:0:8}..."
fi
echo ""

echo "========================================"
echo " ZeroTrace Agent Installation"
echo "========================================"
echo " Controller:  ${CONTROLLER_IP}:${CONTROLLER_PORT}"
echo " Binary repo: ${SERVER_URL}"
if [ -n "${API_KEY}" ]; then
    echo " API Key:     ${API_KEY:0:8}..."
fi
echo ""

# ── OS / Arch detection ───────────────────────────────────────
OS=$(uname -s | tr A-Z a-z)
if [ "$OS" != "linux" ] && [ "$OS" != "darwin" ]; then
    echo "Error: Unsupported OS $OS. Only linux and darwin are supported."
    exit 1
fi

ARCH=$(uname -m)
if [ "$ARCH" = "x86_64" ]; then
    ARCH="amd64"
elif [ "$ARCH" = "aarch64" ] || [ "$ARCH" = "arm64" ]; then
    ARCH="arm64"
else
    echo "Error: Unsupported architecture $ARCH. Only x86_64 and arm64 are supported."
    exit 1
fi

BINARY_NAME="zerotrace-agent-${OS}-${ARCH}"
DOWNLOAD_URL="${SERVER_URL}/agent/binaries/${BINARY_NAME}"

echo " Detected OS:   $OS"
echo " Detected Arch: $ARCH"
echo ""

# ── Create directories ────────────────────────────────────────
echo "→ Creating installation directories..."
sudo mkdir -p "${BIN_DIR}"
sudo mkdir -p "${CONFIG_DIR}"
sudo mkdir -p "${LOG_DIR}"
sudo mkdir -p "${INSTALL_DIR}/tmp"
sudo mkdir -p "${INSTALL_DIR}/var/run"

# ── Stop any existing agent ───────────────────────────────────
if sudo systemctl is-active --quiet zerotrace-agent 2>/dev/null; then
    echo "→ Stopping existing agent..."
    sudo systemctl stop zerotrace-agent || true
fi
# Also kill any running instance
sudo pkill -f "${BINARY_PATH}" 2>/dev/null || true
sleep 1

# Clean up stale eBPF socket from previous runs (avoids "Address already in use")
if [ -S /var/run/zerotrace_bpf_ctrl ]; then
    echo "→ Cleaning up stale eBPF socket..."
    sudo rm -f /var/run/zerotrace_bpf_ctrl || true
fi
# Also clean up the old eBPF ctrl file if it exists
sudo rm -f /usr/bin/zerotrace-ebpfctl 2>/dev/null || true

# ── Write config ──────────────────────────────────────────────
echo "→ Generating config at ${CONFIG_PATH}..."
sudo tee "${CONFIG_PATH}" > /dev/null << EOF
# Generated by install.sh at $(date -u +"%Y-%m-%dT%H:%M:%SZ")

## controller ip
controller-ips:
  - ${CONTROLLER_IP}

## controller listen port
controller-port: ${CONTROLLER_PORT}

## ingester addresses (data plane — L4/L7 flow telemetry)
ingester_ip:
  - ${CONTROLLER_IP}

ingester-port:
  - ${INGESTER_PORT}

## proxy controller
proxy_controller_ip:
  - ${CONTROLLER_IP}

proxy_controller_port:
  - ${CONTROLLER_PORT}

## analyzer
analyzer_ip:
  - ${CONTROLLER_IP}

## logfile path
log-file: ${LOG_DIR}/zerotrace-agent.log
EOF

# ── Tags ──────────────────────────────────────────────────────
if [ -n "${ZT_TAGS}" ]; then
    echo "→ Adding tags: ${ZT_TAGS}"
    echo "" | sudo tee -a "${CONFIG_PATH}" > /dev/null
    echo "vtap_tags:" | sudo tee -a "${CONFIG_PATH}" > /dev/null
    for tag in ${ZT_TAGS}; do
        echo "  - ${tag}" | sudo tee -a "${CONFIG_PATH}" > /dev/null
    done
fi

# ── Write API key to env file (secure) ────────────────────────
if [ -n "${API_KEY}" ]; then
    echo "→ Writing API key to ${ENV_FILE}..."
    sudo tee "${ENV_FILE}" > /dev/null << EOF
# ZeroTrace Agent environment — sourced by systemd / manual runs
ZT_API_KEY=${API_KEY}
EOF
    sudo chmod 600 "${ENV_FILE}"
fi

# ── Register agent with Zerotrace Web ──────────────────────────
# This creates a vtap record in the correct org database so the
# zerotrace-server can associate this agent with the user's org.
if [ -n "${API_KEY}" ]; then
    echo "→ Registering agent with Zerotrace..."
    CTRL_MAC=$(ip link show | grep -oE '([0-9a-f]{2}:){5}[0-9a-f]{2}' | head -1)
    REGISTER_RESP=$(curl -s -X POST "${SERVER_URL}/api/v1/agents/register" \
        -H "Content-Type: application/json" \
        -H "X-API-Key: ${API_KEY}" \
        -d "{\"ctrl_ip\":\"$(hostname -I | awk '{print $1}')\",\"ctrl_mac\":\"${CTRL_MAC}\",\"hostname\":\"$(hostname)\"}" 2>/dev/null)
    if echo "${REGISTER_RESP}" | grep -q '"ok":true'; then
        echo "   ✓ Agent registered"
    else
        echo "   ⚠ Registration failed: ${REGISTER_RESP}"
    fi
fi

# ── Download binary ───────────────────────────────────────────
echo "→ Downloading agent from ${DOWNLOAD_URL}..."
TMP_BIN="/tmp/zerotrace-agent-$$"
curl -f -sL -o "${TMP_BIN}" "${DOWNLOAD_URL}" || {
    echo ""
    echo "Error: Failed to download the agent binary."
    echo "  URL:  ${DOWNLOAD_URL}"
    echo "  Hint: Ensure the zerotrace-web backend is running on port 3001"
    echo "        and agent binaries are placed in backend/agent-installer/binaries/"
    exit 1
}

sudo mv "${TMP_BIN}" "${BINARY_PATH}"
sudo chmod +x "${BINARY_PATH}"
echo "   Binary installed to ${BINARY_PATH}"

# ── Install systemd service (Linux only) ──────────────────────
if [ "$OS" = "linux" ] && [ "${INSTALL_SYSTEMD}" = "true" ]; then
    echo "→ Installing systemd service..."
    sudo tee /etc/systemd/system/zerotrace-agent.service > /dev/null << EOF
[Unit]
Description=ZeroTrace Agent (eBPF-based observability)
After=network.target
Documentation=https://github.com/DeepShield-AI/zerotrace-agent

[Service]
Type=simple
ExecStart=${BINARY_PATH} -c ${CONFIG_PATH}
Restart=always
RestartSec=10
LimitNOFILE=65536
EnvironmentFile=-${ENV_FILE}

# Security hardening
PrivateTmp=yes
NoNewPrivileges=yes
ProtectSystem=strict
ProtectHome=yes
ReadWritePaths=${LOG_DIR} /var/run /run

[Install]
WantedBy=multi-user.target
EOF

    sudo systemctl daemon-reload
    sudo systemctl enable zerotrace-agent

    # ── Start the agent ─────────────────────────────────────────
    echo "→ Starting agent..."
    sudo systemctl start zerotrace-agent

    # Give it a moment then check status
    sleep 2
    if sudo systemctl is-active --quiet zerotrace-agent; then
        echo "   ✓ Agent is running (systemd)"
    else
        echo "   ⚠ Agent may have failed to start. Check logs:"
        echo "     sudo journalctl -u zerotrace-agent -n 20"
    fi

elif [ "$OS" = "linux" ]; then
    # ── Manual start (no systemd) ──────────────────────────────
    echo "→ Starting agent (foreground, no systemd)..."
    if [ -n "${API_KEY}" ]; then
        sudo ZT_API_KEY="${API_KEY}" nohup "${BINARY_PATH}" -c "${CONFIG_PATH}" \
            > "${LOG_DIR}/agent.log" 2>&1 &
    else
        sudo nohup "${BINARY_PATH}" -c "${CONFIG_PATH}" \
            > "${LOG_DIR}/agent.log" 2>&1 &
    fi
    sleep 1
    if pgrep -f "${BINARY_PATH}" > /dev/null; then
        echo "   ✓ Agent is running (pid $(pgrep -f ${BINARY_PATH} | head -1))"
    else
        echo "   ⚠ Agent may have failed to start. Check ${LOG_DIR}/agent.log"
    fi

elif [ "$OS" = "darwin" ]; then
    # ── macOS: just start in background ────────────────────────
    echo "→ Starting agent (macOS background)..."
    if [ -n "${API_KEY}" ]; then
        ZT_API_KEY="${API_KEY}" nohup "${BINARY_PATH}" -c "${CONFIG_PATH}" \
            > "${LOG_DIR}/agent.log" 2>&1 &
    else
        nohup "${BINARY_PATH}" -c "${CONFIG_PATH}" \
            > "${LOG_DIR}/agent.log" 2>&1 &
    fi
    sleep 1
    if pgrep -f "${BINARY_PATH}" > /dev/null; then
        echo "   ✓ Agent is running (pid $(pgrep -f ${BINARY_PATH} | head -1))"
    else
        echo "   ⚠ Agent may have failed to start. Check ${LOG_DIR}/agent.log"
    fi
fi

# ── Done ──────────────────────────────────────────────────────
echo ""
echo "========================================"
echo " ZeroTrace Agent installed successfully!"
echo ""
echo "  Binary:  ${BINARY_PATH}"
echo "  Config:  ${CONFIG_PATH}"
if [ -n "${API_KEY}" ]; then
    echo "  API Key: ${ENV_FILE} (0600)"
fi
echo ""
echo "  Manage with systemd:"
echo "    sudo systemctl status zerotrace-agent"
echo "    sudo systemctl restart zerotrace-agent"
echo "    sudo journalctl -u zerotrace-agent -f"
echo ""
echo "  Or run manually:"
echo "    source ${ENV_FILE}"
echo "    sudo -E ${BINARY_PATH} -c ${CONFIG_PATH}"
echo "========================================"
