#!/bin/bash
set -e

# Default settings — derived from CONTROLLER_IP so it works on remote machines
CONTROLLER_IP=${ZEROTRACE_CONTROLLER_IP:-"202.112.237.37"}
CONTROLLER_PORT=${ZEROTRACE_CONTROLLER_PORT:-"30035"}
SERVER_URL=${SERVER_URL:-"http://${CONTROLLER_IP}:3001"}
INSTALL_DIR="/opt/zerotrace-agent"
BIN_DIR="${INSTALL_DIR}/bin"
CONFIG_DIR="${INSTALL_DIR}/etc"
LOG_DIR="${INSTALL_DIR}/var/log"

echo "========================================"
echo "Starting ZeroTrace Agent Installation..."
echo "========================================"
echo "Controller:  ${CONTROLLER_IP}:${CONTROLLER_PORT}"
echo "Binary repo: ${SERVER_URL}"
echo ""

# Determine OS
OS=$(uname -s | tr A-Z a-z)
if [ "$OS" != "linux" ] && [ "$OS" != "darwin" ]; then
    echo "Error: Unsupported OS $OS. Only linux and darwin are supported."
    exit 1
fi

# Determine Architecture
ARCH=$(uname -m)
if [ "$ARCH" = "x86_64" ]; then
    ARCH="amd64"
elif [ "$ARCH" = "aarch64" ] || [ "$ARCH" = "arm64" ]; then
    ARCH="arm64"
else
    echo "Error: Unsupported architecture $ARCH. Only x86_64 and arm64 are supported."
    exit 1
fi

BINARY_NAME="zerotrace-agent-${OS}-${ARCH}"
DOWNLOAD_URL="${SERVER_URL}/agent/binaries/${BINARY_NAME}"

echo "Detected OS:   $OS"
echo "Detected Arch: $ARCH"
echo "Binary:        ${BINARY_NAME}"
echo ""

# Create installation directories
echo "Creating installation directories..."
sudo mkdir -p "${BIN_DIR}"
sudo mkdir -p "${CONFIG_DIR}"
sudo mkdir -p "${LOG_DIR}"

# Generate configuration file
echo "Generating config at ${CONFIG_DIR}/zerotrace-agent.yaml..."
sudo tee "${CONFIG_DIR}/zerotrace-agent.yaml" > /dev/null << EOF
# Generated by install.sh

## controller ip
controller-ips:
  - ${CONTROLLER_IP}

## controller listen port
controller-port: ${CONTROLLER_PORT}

## ingester addresses
ingester_ip:
  - ${CONTROLLER_IP}

## proxy controller
proxy_controller_ip:
  - ${CONTROLLER_IP}

proxy_controller_port:
  - ${CONTROLLER_PORT}

## analyzer
analyzer_ip:
  - ${CONTROLLER_IP}

## logfile path
log-file: ${LOG_DIR}/zerotrace-agent.log
EOF

# If ZT_TAGS is set, append to config
if [ -n "${ZT_TAGS}" ]; then
    echo "Adding tags: ${ZT_TAGS}"
    echo "" | sudo tee -a "${CONFIG_DIR}/zerotrace-agent.yaml" > /dev/null
    echo "vtap_tags:" | sudo tee -a "${CONFIG_DIR}/zerotrace-agent.yaml" > /dev/null
    for tag in ${ZT_TAGS}; do
        echo "  - ${tag}" | sudo tee -a "${CONFIG_DIR}/zerotrace-agent.yaml" > /dev/null
    done
fi

# Download the binary
echo "Downloading agent from ${DOWNLOAD_URL}..."
sudo curl -f -sL -o "${BIN_DIR}/zerotrace-agent" "${DOWNLOAD_URL}" || {
    echo ""
    echo "Error: Failed to download the agent binary."
    echo "  URL:  ${DOWNLOAD_URL}"
    echo "  Hint: Ensure the zerotrace-web backend is running on port 3001"
    echo "        and agent binaries are placed in backend/agent-installer/binaries/"
    exit 1
}

# Make it executable
sudo chmod +x "${BIN_DIR}/zerotrace-agent"

# Output success message
echo ""
echo "========================================"
echo "ZeroTrace Agent installed successfully!"
echo ""
echo "  Binary: ${BIN_DIR}/zerotrace-agent"
echo "  Config: ${CONFIG_DIR}/zerotrace-agent.yaml"
echo ""
echo "  Run with API key as environment variable:"
echo "    sudo ZT_API_KEY=<your-key> ${BIN_DIR}/zerotrace-agent -c ${CONFIG_DIR}/zerotrace-agent.yaml"
echo ""
echo "  Or with tags:"
echo "    sudo ZT_TAGS=\"env:prod team:backend\" ZT_API_KEY=<key> ${BIN_DIR}/zerotrace-agent -c ${CONFIG_DIR}/zerotrace-agent.yaml"
echo "========================================"
